### ISSUE TITLE
Stabilize inline assembly

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rfcs#1004]
It's needed.

**Comment by kballard** [comment]
Why is it needed? This issue contains absolutely zero information.

**Comment by steveklabnik** [comment]
@kballard we're using the RFC repo to track stuff as they progress. Some issues are pre-pre-RFCs, if that makes sense. So, having an issue to track discussion around the stabilization of this feature is worthwhile. Post beta, I was going to make an issue for each feature gate anyway, so this just knocks one of them out.

**Comment by kballard** [comment]
Ok. That would have been more obvious if the description was something like "Issue for tracking discussion of stabilization of this feature gate", rather than "It's needed".

**Comment by petrochenkov** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/29722
