### ISSUE TITLE
Add default::Default to the (core) prelude

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rfcs#1035]
With CTFE, added backwards compatibly at a later date, this would be very useful for static initialization. No longer, to initialize a StaticMutex, would you have to write

```rust
static ST: StaticMutex = STATIC_MUTEX_INIT;
```

You could instead write

```rust
static ST: StaticMutex = Default::default();
```

This is really useful for standard library writers, because it just looks nicer. It's a small feature, but one that doesn't take anything away from anybody.

You also can just derive(Default) for types that should start out zeroed (for example, my heap implementation currently):

```rust
const HEAP_INIT: Heap =
Heap {
    heap: 0 as *mut u8,
    hptr: 0 as *mut u8,
    size: 0,
};

static HEAP: Heap = HEAP_INIT;

static LOOP_BUFFERS: [Heap; 5] = [HEAP_INIT; 5];
```

Whereas with this change (and CTFE)

```rust
static HEAP: Heap = Default::default();

static LOOP_BUFFERS: [Heap; 5] = [Default::default(); 5];
```

And, with a future, also backwards compatible change which adds in a C++ style `{}` syntax

```rust
static HEAP: Heap = Heap {..};

static LOOP_BUFFERS: [Heap; 5] = [Heap {..}; 5];
```

or something like that.

**Comment by alexcrichton** [comment]
Thanks for the issue! This is actually currently being proposed in #1030 as well, so I'm going to close in favor of that, and feel free to weigh in on the PR!
