### ISSUE TITLE
permit long borrows of constants where possible (rvalue promotion)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rfcs#1056]
@eddyb did a lot of great work identifying constants that can be safely promoted into static values, which we are using to improve our code generation. However, we don't expose this information to the end-user, except in the special case of an empty vector literal like `&[]`. We should fix this!

The main work here is going through the code, writing up the rules found there, and perhaps cleaning them up some for "human consumption".

**Comment by petrochenkov** [comment]
This is implemented and stabilized!
cc https://github.com/rust-lang/rust/issues/38865
