### ISSUE TITLE
Add lint for statically-known out-of-bounds array access

### ISSUE THREAD

**Issue by huonw** [rust-lang/rfcs#1060]
E.g.

``` rust
fn foo() {
    let x = [0; 10];
    println!("{}", x[100]); // warning: index expression is always out-of-bounds
}
```

The minimal viable form would just work with fixed sized arrays `x: [T; n]` and, for `x[m]` expressions, check if `m` is a compile-time constant and `m >= n`.

**Comment by bluss** [comment]
This is now implemented (MIR trans)

```warning: this expression will panic at run-time```
