### ISSUE TITLE
Make FixedSizeArray an unsafe trait

### ISSUE THREAD

**Issue by bluss** [rust-lang/rfcs#1073]
FixedSizeArray will be very useful to handle fixed size arrays in general. For me it would reduce a lot of boilerplate involved in implementing traits for multiple array sizes.

I propose to make it an unsafe trait, so that code can rely on its implementors being fixed size arrays. Often nice optimizations are possible if you know a type is truly an array. 

Examples:
1. Given a `&[T], T: FixedSizeArray`, you don't have to check the lengths of each array, they are same types and must be same lengths
2. Ensure function is only generic over fixed size arrays http://stackoverflow.com/a/29589604

Marking the trait `unsafe` is no inconvenience to the user. It just marks the trait effectively "closed" (only array types will implement it).

**Comment by Centril** [comment]
This was done.
