### ISSUE TITLE
Add PathBuf::clear() mimicking String::clear()

### ISSUE THREAD

**Issue by CrimsonVoid** [rust-lang/rfcs#1080]
Right now there is no easy way to reuse the internal buffer of `PathBuf` which can lead to an alloc/free if the user wants to assign a new PathBuf while retaining ownership. Adding a `clear` method would allow the programmer to write code similar to:

``` rust
let mut s = "Hello world".to_string();
s.clear(); // We can reuse the buffer
s.push_str("Hello");
```

**Comment by kballard** [comment]
It looks like `OsString` doesn't have this capability. I think we need to add more methods to `OsString` first. `clear()` seems like a reasonable one to add. But I'm surprised we don't even have a `reserve()` method (or `shrink_to_fit()`). `PathBuf` could grow the same set of methods too, although we always have the option with `PathBuf` of using `.into_os_string()` to convert it to an `OsString`, manipulating that, and converting back into a `PathBuf` (if `OsString` gained methods that `PathBuf` didn't).
