### ISSUE TITLE
Generate ident of macros to call

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rfcs#1167]
I'm in the process of writing a fast small matrix library in Rust, and I have a bunch of code that looks like this:

```
impl_Mat!(2, 3, Mat2x3, unroll_Mat2x3, Vec2, unroll_Vec2, Vec3, unroll_Vec3, Mat3x2, unroll_Mat3x2);
```

where `unroll_Mat2x3`, `unroll_Vec3`, etc, are other macros. I've tried to use `concat_idents`, but I can't get it to work to generate `ident`s of other macros I can call. I would like to just write:

```
impl_Mat!(2, 3);
```

and just have everything generated automatically.

Something else that would be useful would be a way to convert an `int` to an `ident`. Currently there's no way to unroll loops except to do it for each possible count (`unroll_2`, `unroll_3`, etc), so the only way is to fake it by manipulating `uint`s to `ident`s.

**Comment by dtolnay** [comment]
Let's continue to track this as part of the work on the `concat_idents` feature. https://github.com/rust-lang/rust/issues/29599
