### ISSUE TITLE
Add init and tail to Iterator trait

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rfcs#1186]
Currently `Vec` has `init` and `tail`, it would also make sense to add those to the Iterator trait.

**Comment by bluss** [comment]
tail is `.skip(1)`, init is more complicated (requires one item lookahead, which you can do with Peekable). I'm a bit sceptical of their utility.

**Comment by mbrubeck** [comment]
Historical note: `Vec::init` and `tail` were never stabilized, they were deprecated in favor of `split_first` and `split_last`.

**Comment by Centril** [comment]
Since they were removed from `Vec` I'd say this issue is moot now and so I'll close this.
