### ISSUE TITLE
[Proposal] `unless` keyword as if not

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rfcs#1310]
I'd like to write
```
unless flag || anotherFlag || someCondition {
}
```
instead of
```
if not (flag || anotherFlag || someCondition) {
}
```

**Comment by BurntSushi** [comment]
`if not (...)` is not valid Rust. It's `if !(a || b || c)`.

(I'm against this. Just use `if !(...)`.)

**Comment by reem** [comment]
The primary reason this might be helpful is for `unless let`, but that's a different conversation.
