### ISSUE TITLE
[Proposal] exchange for Vec

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rfcs#1316]
I suggest `exchange` method for Vec.
```
fn exchange(&mut self, old_item_index: usize, new_item: T) -> T
```
It should make same as `swap_remove`, but with specified item

**Comment by glaebhoerl** [comment]
I think this is just the same as `mem::replace(&mut vec[old_item_index])`?

**Comment by killercup** [comment]
What should happen when `old_item_index` is out of bounds?

---

Also, this is basically the same as:

```rust
let mut xs = vec!["lorem", "ipsum", "dolor", "sit"];
xs[1] = "amet";
```

**Comment by KalitaAlexey** [comment]
Probably it is. I did not know about it.
