### ISSUE TITLE
[Proposal] #exclude_from_comparison attribute

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rfcs#1345]
Let's consider the struct
```
struct List {
    name: String,    
    items: RefCell<Vec<Item>>,
}
```
Let's consider we need to compare two instances of List. We cannot use `#[derive]` to implement comparison, because `RefCell` has no impl for comparison. If we want to compare with `name` field we must manually implement all required traits.
I suggest `#[exclude_from_comparison]` attribute.
If I had the `#[exclude_from_comparison]` attribute, then I will write
```
#[derive(PartialEq)]
#[derive(Eq)]
#[derive(PartialOrd)]
#[derive(Ord)]
struct List {
    name: String,
    #[exclude_from_comparison]
    items: RefCell<Vec<Item>>,
}
```

**Comment by apasel422** [comment]
See also rust-lang/rust#8258.

**Comment by KalitaAlexey** [comment]
Seen. I got it.
