### ISSUE TITLE
Expose `core::intrinsics::abort` as `std::process::abort`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rfcs#1363]
This would be a safe wrapper around the intrinsic.

**Comment by nagisa** [comment]
Semantics of this intrinsics are significantly more different compared to C
abort, so I'm not sure whether this implementation strategy is the best one
to take.

**Comment by Stebalien** [comment]
I don't know the details of abort but I'd like some safe wrapper.

**Comment by Gankro** [comment]
Even a *stable* wrapper would be grand :)

**Comment by fitzgen** [comment]
This would be super helpful for wasm stuff, where panics and aborts translate into traps either way, but panics pull in all the formatting and panicking infrastructure, which adds something like 30-40K to binary size.

Anything I can do to help push this forward?

**Comment by fitzgen** [comment]
Er wait, I'm not thinking of `std::process::abort`, which already exists.

I'm thinking of a stable `core`/`#![no_std]` story for `abort`. Maybe that is a separate issue somewhere?

**Comment by nagisa** [comment]
https://github.com/rust-lang/rust/issues/44489 is where you’d want to discuss panic infrastructure and it pulling in formatting machinery unnecessarily.

**Comment by Centril** [comment]
This is done since `std::process::abort` is stable.

**Comment by nagisa** [comment]
`std::process::abort` is stable, but it is not `std::intrinsics::abort`. It is not clear though if the original request was for a stable wrapper around `std::intrinsics::abort` or for anything that could be used like an abort.

**Comment by Centril** [comment]
@nagisa Weird, the documentation says: "The stabilized version of this intrinsic is std::process::abort".

https://doc.rust-lang.org/nightly/std/intrinsics/fn.abort.html

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/2512.
