### ISSUE TITLE
Use [x; n] syntax for non-Copy types

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#1366]
Originally at https://github.com/rust-lang/rust/issues/5244

**Comment by Gankro** [comment]
The title of this issue implies making this work for all arbitrary non-Copy types. Is `clone` a lang item yet? If not, this would necessitate that. Unless the desugar is to textually duplicate `x` and evaluate it `n` times, but that would be contrary to how `vec!` desugars.

However the original issue referenced was just about making enum variants that only contain Copy data behaving as Copy types for the purposes of array literals. The canonical example being `None`, which is always producable, no matter what type the Option wraps.

**Comment by Kimundi** [comment]
I think the intention was "make the `[x; n]` syntax accept either `Copy`able types or constexprs".

This would never run user code, but still enable the usecase of, for example, initializing a array of Options to non-copyable data.

(`static X: Option<Box<()>> = None;` compiles today for the same reasoning)

**Comment by Ticki** [comment]
Big :+1: here. I've needed this many times.

**Comment by Ticki** [comment]
Dup of #1109?

**Comment by steveklabnik** [comment]
yes, it is.
