### ISSUE TITLE
Make Clone a lang-item and implement it for closures whose members are all Clone

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rfcs#1369]
moved from rust-lang/rust#23501

**Comment by withoutboats** [comment]
Could this be implemented using default impls of `Clone` and `Copy`? I know that would be a pretty serious breaking change, because there could be types that are only sound because they don't implement `Clone`. But in principle, wouldn't closures be `Clone` if their environment is `Clone` if that were the case (or do default impls not apply to closures)?

**Comment by jonas-schievink** [comment]
This is also needed to fix rust-lang/rust#28229

**Comment by mitchmindtree** [comment]
Just thought I'd :+1: this and mention a couple use-cases I come across quite frequently:
- Iterator ergonomics - being able to clone Iterators with some `F: Fn + Clone` field
- real-time thread synchronisation - being able to clone a `F: Fn(&mut State) + Clone` and send it to multiple real-time threads across via channels without requiring `Arc`

**Comment by J-F-Liu** [comment]
Meet this same issue, here is an example:
```rust
#[derive(Debug)]
struct Take(String);

fn make<F>(func: F) -> Box<Fn(&str) -> Take>
    where F: FnOnce(String) -> Take + Copy + 'static
{
     Box::new(move |s| {
         func(s.to_string())
     })
}

fn main() {
    let m = make(|s|Take(s));
    println!("{:?}", m("abc"));
}
```
should compile.

**Comment by russellmcc** [comment]
I've started hitting this a lot, mostly in the "iterator ergonomics" that @mitchmindtree mentioned.  I'm not sure why `Clone` needs to be a lang item (maybe there's something I'm missing), but having appropriate closures implement `Clone` sure would be convenient.

**Comment by cramertj** [comment]
I've written this up as https://github.com/rust-lang/rfcs/pull/2132.

**Comment by scottmcm** [comment]
Since the RFC was accepted, closing in favour of the tracking issue https://github.com/rust-lang/rust/issues/44490
