### ISSUE TITLE
Find a way to specify arbitrary attributes on derived impls

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rfcs#1382]
Spawned from https://github.com/rust-lang/rust/issues/18969

cc https://github.com/rust-lang/rust/pull/20236

**Comment by keeperofdakeys** [comment]
The only way I can see this working is being able to create a doc attribute that references an items name/type, like `#[doc = "Foobar", target = Foobar::new]`. Though I'm not sure how that would work for trait impls.

**Comment by petrochenkov** [comment]
There's not too much motivation for specifying attributes on derived impls now, so I'm going to close this.
