### ISSUE TITLE
Pattern matching & define or return Err

### ISSUE THREAD

**Issue by eladn** [rust-lang/rfcs#1407]
Assuming we have a function that returns Result<T, E> for certain types named T, E.
Now we want to do the following:

```
if let Some(x) = optional1 {
  if let Some(y) = optional2 {
    // ...
  } else {
    return Err(NonMatchBind)
  }
} else {
  return Err(NonMatchBind)
}
```

Suggestion: so that if optional1/optional2 don't match the suggested pattern (in this case- not a Some(_) but a None), the function will return Err(NonMatchBind). Otherwise, the function will continue to following instructions.
```
let Some(x) =? optional1;
let Some(y) =? optional2;
// ...
```

What do you think?

Elad Nachmias

**Comment by leodasvacas** [comment]
Take a look at #1303.

**Comment by nrc** [comment]
I believe this is addressed by the `?` operator.
