### ISSUE TITLE
Error E0046 should be the last one to report

### ISSUE THREAD

**Issue by shahuwang** [rust-lang/rfcs#1466]
```
struct Context;  

trait ctx{
  
  fn f1(&self) -> String;  

  fn f2(&self) ;
   
}
  
impl ctx for Context{ 
 
  fn f1(&self) -> String{
  
     // code here
  
  }
  
}   
```
During coding, I always need to run 'cargo build' to check whether it is right, but for the code above, it always report  "error: not all trait items implemented, missing: `f2` [E0046]
error: aborting due to previous error",   

It is ok that only one or two methods of the trait that need to be implemented,but if the trait has ten methods, I have to implement all of them before I can check whether method f1 is implemented right, without syntax error.

I wish that E0046 be reported as the last one.

**Comment by Ticki** [comment]
This is more fitting for a rust issue, than a rfc.

**Comment by shahuwang** [comment]
@Ticki Thanks
