### ISSUE TITLE
Add 'is_empty' method for 'std::path::Path'

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rfcs#1497]
Related to https://github.com/rust-lang/rust/pull/31231

**Comment by tshepang** [comment]
But this was done on that linked PR?

**Comment by untitaker** [comment]
Proper rationale here: https://github.com/rust-lang/rust/issues/30259

IMO it doesn't really make any semantical sense for a path to be empty, and adding `is_empty` breaks the abstraction.

**Comment by Ticki** [comment]
Is this _really_ worth an RFC? I mean this is an incredibly small issue, and doubt anyone would be against it.

**Comment by frewsxcv** [comment]
@alexcrichton Should I/we bother with the RFC dance here or can I/we assume that https://github.com/rust-lang/rust/pull/31231#issuecomment-182665764 is confirmation of acceptance about `Path::is_empty`

**Comment by alexcrichton** [comment]
Yeah this is probably fine without an RFC (it'll start out as unstable anyway)

**Comment by frewsxcv** [comment]
Cool, I'll open a PR for this in rust-lang/rust then.
