### ISSUE TITLE
Contradiction in RFC1192 (Inclusive Ranges)

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rfcs#1537]
The "Detailed design" section mentions
> Writing ...b in an expression desugars to std::ops::RangeToInclusive { end: b }.

However, the "Alternatives" sections states
> This RFC doesn't propose non-double-ended syntax, like a..., ...b or ... since it isn't clear that this is so useful. Maybe it is.

From what I have gathered, the specified design has been implemented.

**Comment by durka** [comment]
Hmm, you're right. I did implement `a...b` and `...b`. My understanding is `a...` is reserved for possible variadic generic syntax In The Future.

There was [discussion](https://github.com/rust-lang/rfcs/pull/1192#issuecomment-119611977) in the RFC about `...b`, and the text was [updated](https://github.com/rust-lang/rfcs/pull/1192#issuecomment-127363498) but some parts missed as you noticed.

cc @aturon
