### ISSUE TITLE
Add as_millis function to std::time::Duration

### ISSUE THREAD

**Issue by paezao** [rust-lang/rfcs#1545]
Hello,

It's funny because there's a from_millis function but not an as_millis one.

What do you guys think? It's a simple change.

Cheers

**Comment by nagisa** [comment]
You cannot convert duration to milliseconds losslessly whereas you can do that in the other direction.

**Comment by Ticki** [comment]
@nagisa of course not, but it would still be very useful, nonetheless. An `as_nanos` would be very useful too.

**Comment by gkoz** [comment]
The [duration RFC](https://github.com/rust-lang/rfcs/blob/master/text/1040-duration-reform.md) explicitly mentions acceptable losses:

> In general, this proposal considers it acceptable to reduce the granularity of timeouts (eliminating nanosecond granularity if only milliseconds are supported) and to truncate very large timeouts.

So it is surprising that everyone has to implement the reductions manually.

**Comment by Ticki** [comment]
Yes, this patttern is virtually everywhere.

**Comment by Ticki** [comment]
See https://github.com/rust-lang/rfcs/pull/1547

**Comment by robinst** [comment]
Looks like with https://github.com/rust-lang/rust/issues/35118 (`u128`) landing, this would be possible without having to truncate large values.

**Comment by pornel** [comment]
The rounding problem is nonsense. `.as_millis()` can express 584.9 million years in `u64`.

What is a realistic use case for needing millisecond precision on a duration longer than half a billion years?

**Comment by clarcharr** [comment]
Perhaps we could offer `subsec_millis` and `subsec_micros` instead? It'd be nice to have something like that.

**Comment by lolgesten** [comment]
I think the time handling in rust a pretty serious ergonomic issue. To easily do a `System.currentTimeMillis()` or `Date.now()`, you have to pull in 3rd party crates or write several lines of code.

So whilst I agree rust std should stop short of full blown `chronos` time handling/formatting, milliseconds (and epoch) are so common they ought to be there.

**Comment by idubrov** [comment]
Totally agree. It's an ergonomic issue. Call me stupid, but this is the code I had to fix today:

```rust
let sec = (elapsed.as_secs() as f64) + f64::from(elapsed.subsec_nanos()) / 1000_000.0;
```

See the issue? It worked fine until our queries became too long. 🤥

**Comment by praetp** [comment]
Any progress on this ?

**Comment by kornelski** [comment]
I've created a poll about it https://internals.rust-lang.org/t/duration-as-milliseconds/7605

**Comment by lolgesten** [comment]
And there is this: https://github.com/rust-lang/rust/pull/50167

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/50202.
