### ISSUE TITLE
Derive implementations for From and operator traits.

### ISSUE THREAD

**Issue by JelteF** [rust-lang/rfcs#1625]
As a follow up to #1551 I created this library: https://github.com/JelteF/derive_more
It allows to derive implementations for `From` and operator traits for basic, structs and enum types. 
It's missing some operators still. Most notably the unary operators (`Neg`, `Not`) and the `Assign` variants of the operators.

I think these implementations would make a lot of sense to have in the standard library as they use implement common standard library traits. If you guys agree I have no problem writing an RFC for them.

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/2026 to reduce clutter.
