### ISSUE TITLE
What's the progress of Procedure Macros?

### ISSUE THREAD

**Issue by lygstate** [rust-lang/rfcs#1670]
1.
http://ncameron.org/blog/macros-in-rust-pt1/
2.
http://www.ncameron.org/blog/macros-in-rust-pt2/
3.
http://www.ncameron.org/blog/macros-in-rust-pt3/

**Comment by nrc** [comment]
See this set of RFCs: https://github.com/rust-lang/rfcs/pulls/nrc (not all are proc macros, but most are). There is some implementation work happening too, starting with refactoring of the way libsyntax handles tokens.

**Comment by steveklabnik** [comment]
Closing as this isn't a bug. (Posting on internals.rust-lang.org is the right place to ask these kinds of questions)
