### ISSUE TITLE
Wrong link in #0019

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang/rfcs#1837]
The text of [#0019](https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md) at [**The `Copy` and `Sized` Traits**](https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md#the-copy-and-sized-traits) reads:

> This RFC does not propose any changes to those two traits but rather relies on the specification from [the original opt-in RFC](https://github.com/rust-lang/rfcs/blob/master/text/0003-opt-in-builtin-traits.md).

That link goes nowhere, and [#0003](https://github.com/rust-lang/rfcs/blob/master/text/0003-attribute-usage.md)… isn't OIBITs. 😬 Someone know what the correct link is?

**Comment by Centril** [comment]
I don't think we'll ever found out; so I'm closing this =P
