### ISSUE TITLE
Lifetime elision for `impl`

### ISSUE THREAD

**Issue by ticki** [rust-lang/rfcs#1950]
In similar style as `fn`s unspecified lifetime parameters should all bind to a hidden parameter.

**Comment by steveklabnik** [comment]
This was already accepted in RFC 411 https://github.com/rust-lang/rfcs/blob/master/text/0141-lifetime-elision.md

Nobody has implemented it yet. It's being tracked here https://github.com/rust-lang/rust/issues/15872
