### ISSUE TITLE
Allow usage of core crate in non no_std crates

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rfcs#2162]
Currently, crates that conditionally enable `no_std` must also use *either* the `core` crate or the `std` crate to access functionality across both crates. For example, boilerplate such as:

```rust
#[cfg(feature = "std")]
use std::fmt;
#[cfg(not(feature = "std"))]
use core::fmt;
```

seems extremely excessive. It'd be nice if, because the `std` crate depends on libcore anyway, that the `core` crate be made accessible to all programs, including those without the `no_std` flag enabled.

**Comment by SimonSapin** [comment]
Doesn’t this work?
```rust
extern crate core;
use core::fmt;
```

**Comment by clarcharr** [comment]
…yes it does.
