### ISSUE TITLE
Key binding to defocus the search bar in Rustdoc pages

### ISSUE THREAD

**Issue by Sogomn** [rust-lang/rfcs#2265]
The key bindings in Rustdoc pages are very useful and allow quick navigation. However, after pressing the `S` key, it's not possible to defocus the search bar, making it impossible to scroll down using the arrow keys.
I propose an addition to the key bindings so that the escape key makes the search bar lose focus.

**Comment by untitaker** [comment]
I don't think this requires an RFC, but I am not sure.

**Comment by Sogomn** [comment]
rust-lang/rust#47134
