### ISSUE TITLE
More path suggestions for when a struct field doesn't exist

### ISSUE THREAD

**Issue by Nokel81** [rust-lang/rfcs#2472]
See [this playground](https://play.rust-lang.org/?gist=a9ed0de07b291c953bd8e4fdfb8b8669&version=stable&mode=debug):

Currently, if someone tries to reference a field that doesn't exist in the current struct an error is produced and recommendations are provided, this is wonderful.

However, I think that it could be made even better by adding some addition suggestions. What would these be?

Referring back to my first example I would say that having `'state.tokens'` in addition to the other names would be beneficial. To do this, if this error comes up then the the tree which is the name paths of the fields of each of the structs is traversed in order to find these additional suggestions.

Caveats: 
1. Structs that are not 'pub' should not be traversed through. I say this so that such things which cannot be recommended if they cannot be actually accessed.
2. There should be a default depth, say 5, which is configurable either on the command line or when using cargo

**Comment by Centril** [comment]
I highly recommend taking this to the internals forum instead if you want more eyes on it :)
