### ISSUE TITLE
String::from(“…”) => d”…” 

### ISSUE THREAD

**Issue by AmjadHD** [rust-lang/rfcs#2559]
Dynamic Strings are common but using `String::From("...")` or `"...".to_string()` can get tedious, so it'll be more productive to write a string litteral `d"..."` instead. It's more productive, removes the apparent distance between both types of strings and it's syntactically sweeter.

**Comment by Centril** [comment]
Note that this does not constitute a formal RFC proposal; those are pull requests that follow the [template](https://github.com/rust-lang/rfcs/blob/master/0000-template.md).

Please read the [README.md](https://github.com/rust-lang/rfcs/blob/master/README.md) file to see how the process works.

I'm closing this issue in favor of https://internals.rust-lang.org/t/string-from-d/8528.
