### ISSUE TITLE
Type annotation for two function variables at the same time

### ISSUE THREAD

**Issue by midnio** [rust-lang/rfcs#2567]
Just type annotation for two variables at the same time.

```rust
fn gcd(a, b: i32) {
    ...
}
```

**Comment by Centril** [comment]
I would recommend refiling this at https://internals.rust-lang.org/ to discuss things.

**Comment by scottmcm** [comment]
We cannot do this for closures, as this already works:
```rust
    let f = |a, b: i32| {};
    f("hello", 1);
```
As such, I don't think we should do this for functions either.

**Comment by Centril** [comment]
> As such, I don't think we should do this for functions either.

Agreed, and closing the issue therefore.

**Comment by scottmcm** [comment]
(Note that while I'm not in favour of this specific proposal, I'm certainly interested in options for decreasing verbosity of function definitions, if they can be done while maintaining sufficient clarity.)
