### ISSUE TITLE
A (may be?) fork of a brilliant win-32/Linux/BSD i386/amd64/arm  GUI library & IDE as GUI lib for Rust

### ISSUE THREAD

**Issue by IvankoB** [rust-lang/rfcs#2621]
The library has excellent database support, only needs core OS & GUI libraries to work etc, RPC & remote form features, secure channels, etc

The web site: http://msegui.com/
The main repo: https://gitlab.com/mseide-msegui/mseide-msegui.git
This (Free Pascal) project were created and maintained by a single person (Martinn Schreiber) which suddenly died at Nov  2018

https://gitlab.com/mseide-msegui/mselang.git
This is  Martin's 90% made work on more suitable language for the msee+msegui.  

http://gitorious.org/mseuniverse/mseuniverse
This is a multiple commmiters repo of some documentation, working & example projects , extensions etc. 
The famliy of Martin has passwords to his repos & agrees to share these to new maintainers & forkers if needed. 
The current community around this library ins't skilled enough to continue developing the existing (Free Pascal) code base

**Comment by nagisa** [comment]
This repository is about the language design and changes to the compiler and thus is a wrong place to discuss the wider ecosystem. A better place for such an RFC would be [users.rlo](https://users.rust-lang.org/) or, perhaps, [reddit](https://www.reddit.com/r/rust/).
