### ISSUE TITLE
Add a new file crate.rs to replace lib.rs

### ISSUE THREAD

**Issue by Allenyn** [rust-lang/rfcs#2651]
Add a file crate.rs to subscribe the crate library. 
Is it more clearer vs lib.rs ?

And main.rs no need to redefine the mod which in the crate.rs.  A file with main function will be build to a executable file.
Make crate.rs file the only root of the crate.

That's just my advice. Thanks

**Comment by memoryruins** [comment]
I apologize if I missed your point or you already are aware of the below:

If `crate.rs` is preferred, the path can be changed in `Cargo.toml`,
```toml
[lib]
path = "src/crate.rs"
```
I'm not certain what you mean by redefine the mod, but you can add a `src/bin/main.rs` without changing `lib.rs`, which can then use the public api of your crate. To execute, use `cargo run`.

Additional options are in The Cargo Book 
https://doc.rust-lang.org/cargo/reference/manifest.html#the-project-layout
