### ISSUE TITLE
Proposal: Coroutines with Async: an easy way of sync an async

### ISSUE THREAD

**Issue by tema3210** [rust-lang/rfcs#2660]
All of us know that both coroutines and async\await is desirable features. 
Some of us complained to fact that these two aren't composable enough.
That's right: the main reason of it is that generators basically are sync, when async\await - async).

### Proposal:
My proposal is to make some special case of generator(can't tell about syntax):
1)The generator which yields `await!{...}` should select from features.
2)Such case should block thread until at least one of futures is ready(and yield its result).

The benefits are following:
1)It will allow us to write less async code(that's because async code can be turned to spaghetti much easier)
2)It will allow us to create nice async iterators, and write sync-like asynchronous code.

**Comment by cramertj** [comment]
The async working group and the language design team have been working in cooperation to develop a design for asynchronous generators. If you're interested in joining the discussion, I'd encourage joining the wg-net-async discord channel and joining in discussion there.
