### ISSUE TITLE
NLL RFC Layer 1: Control-flow within a function: Issue with the example

### ISSUE THREAD

**Issue by saleemjaffer** [rust-lang/rfcs#2680]
In the [RFC](https://github.com/rust-lang/rfcs/blob/master/text/2094-nll.md#layer-1-control-flow-within-a-function) for NLL 
```rust
let mut foo: T = ...;
let mut bar: T = ...;
let p: &T;

p = &foo;
// (0)
if condition {
    print(*p);
    // (1)
    p = &bar;
    // (2)
}
// (3)
print(*p);
// (4)
```

The `let p: &T` should be a `let mut p: &T`

**Comment by jonas-schievink** [comment]
Feel free to send a PR with the fix!
