### ISSUE TITLE
Shortcut for Result<T, E> handling at the syntax level

### ISSUE THREAD

**Issue by sirkon** [rust-lang/rfcs#2727]
Hi!

There a proposal about `try` macro for Go recently. It was rejected fortunately. Several language agnostic ideas were formulated within a discussion though, the main was one about what is happening in a well written network service/database/etc when some of resources it uses becomes unavailable: it tries to report about an issue, with as much context as possible. And this basically needs manual handling at every step. The proposed `try` macro, just like `try!` macro and `?` operator in Rust encourages leaving error without annotation.

So, how the good practice would  look like today in Rust? It will be full scale `match`:

```rust
match File::open(name) {
    Ok(file) => ...;
    Err(err) => ...;
}
```

Not that bad at the first glance. But imagine function which decodes config  from a file of certain name and returns some object. This will be match in match:

```rust
match File::open(name) {
    Ok(file) => {
        let res = serde_json::from_reader(file);
        match res {
            Ok(cfg) => cfg;
            Err(err)   => <decoding config from name: err>;
        }
    }
    Err(err) => <open config: err>;
}
```

Well, some may insist this is ok, but it is not. And what if decoder could only read from string? Another level of nesting? 

So, `match` is great for decomposing items of AST, but it really isn’t for error processing.

Now a proposal:

```
let mut file = File::open(name) on err {
    // return annotated error here
}
return serde_json::from_reader(file) on err {
    // return annotated error here
}
```
Where `err` references itself in `Err(err)` branch. And there should a restriction for this `on` block: **it either must leave the scope `file` variable appears in or continue the happy path with `continue <file variable>` statement.**

More formal:

* Postfix operator `on <identifier> <error processing block>` working on `Result<T, E>` value which either returns value of type `T` or leaves the scope.
* <error processing block> is a piece of code which either leaving the current scope somehow (return, break, continue) or “continues” it with a value of type `T` via extended `continue` statement: `continue <value of type T>`.

Advantages of this approach:

1. Full type safety within flat code structure 

Disadvantages:

1. Grammar and flow analyzer complication

So, what do you think?

**Comment by KrishnaSannasi** [comment]
How is this better than `res.map_err(...)?`
