### ISSUE TITLE
 RFC: Rust Symbol Mangling (v0) #2603 Page 404

### ISSUE THREAD

**Issue by serak** [rust-lang/rfcs#2925]
RFC: Rust Symbol Mangling (v0) #2603 Render Link throws Page 404

**Comment by sivizius** [comment]
there is a »rust-« missing, should be https://github.com/rust-lang/rfcs/blob/master/text/2603-rust-symbol-name-mangling-v0.md

**Comment by scottmcm** [comment]
Looks like mbrubeck fixed this.
