### ISSUE TITLE
Add a compiler warning on `&[char]`

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rfcs#2926]
Never ever use `&[char]`.

**Comment by lzutao** [comment]
This repo is for RFC only. The rustc/clippy repo is more appropriate.
But why ?

**Comment by SoniEx2** [comment]
99.99% of the time, `&[&str]` is more appropriate.

because you rarely ever want O(1) indexing on *codepoints*. it turns out O(1) indexing on *characters* is more likely to be what you need. and those can be multiple codepoints.

**Comment by BurntSushi** [comment]
I don't see any good reason to add a _compiler_ warning against the use of a `&[char]`. If you want to pursue this more earnestly, I'd recommend trying to add it as a Clippy lint at first. In light of that, I'm going to close this.
