### ISSUE TITLE
Is a Visual Studio extension planned?

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rfcs#3056]
I do not mean Visual Studio Code but Visual Studio Community/Professional/Enterprise

**Comment by Kixiron** [comment]
The RFC repo isn't really for questions, I would ask on the [Rust Analyzer](https://github.com/rust-analyzer/rust-analyzer) repo.

**Comment by ehuss** [comment]
Questions might be better directed to one of the forums or chat platforms.  Closing as it looks like this was answered on the RA issue.
