### ISSUE TITLE
#TooVerbal

### ISSUE THREAD

**Issue by sankar-boro** [rust-lang/rfcs#3111]
Instead of writing #[derive(Clone, Debug)] can we do something like #Clone#Debug. Modern syntax for modern programming language. Right now #[derive(Clone, Debug)] is too verbal.

**Comment by SOF3** [comment]
Then what do you suggest to happen to attributes?
Nevertheless, I agree that attribute macros and derive macros do not need an explicit separation. Derive macros could totally be implemented as attribute macros, just with the guarantee that they do not modify the annotated item itself, but this is not necessarily something that the user cares.

**Comment by steveklabnik** [comment]
It is unlikely we will make this change, though anyone could make an RFC for it if they wished.

**Comment by kennytm** [comment]
see also #208 and #386 for previous (failed) attempts.
