### ISSUE TITLE
Syntax of mangled names is outdated

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rfcs#3112]
I noticed that [the syntax of mangled names specified in RFC 2603](https://rust-lang.github.io/rfcs/2603-rust-symbol-name-mangling-v0.html#syntax-of-mangled-names) is outdated. Specifically, it does not match the implementation of https://github.com/alexcrichton/rustc-demangle/.

Here are some differences I have observed from rustc-demangle:

1. `<binder>` is optional in `<fn-sig>` and `<dyn-bounds>`;
2. `<const-data>` may contain an optional `"n"` character to indicate negative values.
3. The placeholder variant of `<const>` does not contain a `<type>` item.

Also, the symbol after `<fn-sig>` is `:=` while the symbol after other non-terminals are `=`.

**Comment by michaelwoerister** [comment]
Thanks for the bug report, @EFanZh!
