### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by mr-eyes** [rust-lang/rfcs#3187]
This Medium story link is broken.

https://github.com/rust-lang/rfcs/blob/dc3800810bff9c3f26a52a1e026db26b7c774e40/text/1884-unstable-sort.md?plain=1#L57

**Comment by nagisa** [comment]
This is available on [wayback machine](https://web.archive.org/web/20181006113551/https://medium.com/@topLayoutGuide/a-swift-sorting-problem-e0ebfc4e46d4), we could replace the link to this. That said, this probably is a good cautionary tale about referencing 3rd party resources in RFCs.
