### ISSUE TITLE
Counted looping with `loop`

### ISSUE THREAD

**Issue by zim0369** [rust-lang/rfcs#3330]
Looping for a certain number of times without keeping track of a variable is significantly common.
This could be accommodated in the `loop` keyword's syntax:
```rust
loop 20 {
// This will loop exactly 20 times
}
```
This is  easier than writing:
```rust
for _ in 0..20 { }
```

**Comment by Lokathor** [comment]
I don't think this is a significant improvement. If you really wanted this you could macro it

just typing an approximate version of what you might want on my phone, the macro could be:
```rust
macro_rules! loop_n {
  ($times:expr, $body:block) => {
    for _ in 0..$times $body
  }
}
```
