### ISSUE TITLE
Is it necessary to change the name for mod.rs?

### ISSUE THREAD

**Issue by akf00000** [rust-lang/rfcs#3333]
There is mod.rs every where. I can't know this mod.rs is belong to which crate, I have to see it path. Every time i want to open som crate's mod.rs, i can't locate it by file name immediately, I should find the exactly path in the editor browser.
Is it necessary to change the name for mod.rs? like mod_dir_name.rs or just dir_name.rs?

**Comment by shepmaster** [comment]
Please read [*The Rust Programming Language* — Alternate File Paths](https://doc.rust-lang.org/book/ch07-05-separating-modules-into-different-files.html#alternate-file-paths)
