### ISSUE TITLE
Clarify what needs an RFC

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rfcs#35]
In https://github.com/rust-lang/rfcs/pull/33#issuecomment-39631407, @cmr said:
> Also, I don't think this deserves an RFC. RFCs should be for language changes and changes to items marked `#[stable]`, I think.

It wasn’t clear to me based on https://mail.mozilla.org/pipermail/rust-dev/2014-March/008973.html (see also #31) if #33 required an RFC or not. It generated more discussion that I would have expected, but that discussion could just as well have happened in the main issue tracker.

> ## When you need to follow this process
>
> You need to follow this process if you intend to make "substantial" 
> changes to the Rust distribution. What constitutes a "substantial" 
> change is evolving based on community norms, but may include the following.
> 
>    - Any semantic or syntactic change to the language that is not a bugfix.

This changes libraries, but not the language.

>    - Changes to the interface between the compiler and libraries, 
> including lang items and intrinsics.

Nope.

>    - Additions to `std`

Change, not addition.

> Some changes do not require an RFC:
> 
>    - Rephrasing, reorganizing, refactoring, or otherwise "changing shape 
> does not change meaning".

Unsure about that one. Does `MaybeOwned` have the same "meaning" as `~str`?

>    - Additions that strictly improve objective, numerical quality 
> criteria (warning removal, speedup, better platform coverage, more 
> parallelism, trap more errors, etc.)

I could make up a micro-benchmark with a numerical result, but there are also drawbacks.

>    - Additions only likely to be _noticed by_ other developers-of-rust, 
> invisible to users-of-rust.

This will definitely be noticed by users.

**Comment by alexcrichton** [comment]
We've since grown a lot of language about this, and now we've got a [whole README section](https://github.com/rust-lang/rfcs#when-you-need-to-follow-this-process) dedicated to this, so closing.
