### ISSUE TITLE
Consider adding an Iterator-like Entry API to give sugary methods

### ISSUE THREAD

**Issue by huonw** [rust-lang/rfcs#353]
The deprecation of methods like `find_or_insert` resulted in more verbose code (needing more imports too), e.g. `hash_map.find_or_insert(key, vec![]).push(value)` becomes

```rust
use std::collections::hashmap;

match hash_map.entry() {
     hashmap::Occupied(o) => o.into_mut().push(value),
     hashmap::Vacant(v) => { v.set(vec![value]); }
}
```

which is slightly annoying. We could have an `Entry` trait that has an interface sufficient to have default methods for functionality like the old `find_or_insert` (like Iterator just has the `next` method which is enough for things like `map` & `collect` etc), so the above would become 

```rust
hash_map.entry().get_or_insert(vec![]).push(value);
```

This would also mean that all entries get these methods, avoiding the historical problem of `HashMap` having everything, with `TreeMap` missing a lot.

(We should keep the requirements for the basic `Entry` trait as minimal as possible, so it can be used as widely as possible; if there is fancy functionality that needs more restrictions, we can theoretically have extra traits, similar to `DoubleEndedIterator` etc.)

**Comment by Gankro** [comment]
We got `get` on the enum in collections v2. Can this be closed?

**Comment by aturon** [comment]
Closing, this is done.
