### ISSUE TITLE
is_some_and takes ownership of the value add an API which works by reference

### ISSUE THREAD

**Issue by Havunen** [rust-lang/rfcs#3548]
Hi,

I have noticed a repeating pattern where I have Optional value and I need to check if the value exists and then something else. 
For example, if the value exists and equals "foo" then proceed otherwise skip the condition.

The current implementation of `is_some_and` takes ownership of the value provided which is causes issues and the code does not need ownership for just checking the value. 

current implementation:

```rs
    pub fn is_some_and(self, f: impl FnOnce(T) -> bool) -> bool {
        match self {
            None => false,
            Some(x) => f(x),
        }
    }
```

Maybe something similar could be implemented to the standard library:

```rs
pub fn is_some_and_ref<T>(item: &Option<T>, f: impl FnOnce(&T) -> bool) -> bool {
    match item {
        None => false,
        Some(x) => f(&x),
    }
}
```

**Comment by fmease** [comment]
You can just do `.as_ref().is_some_and(…)`.

**Comment by Havunen** [comment]
Oh right! Thats perfect!
