### ISSUE TITLE
`letm` as a syntactic sugar for `let mut`

### ISSUE THREAD

**Issue by abhijeetbhagat** [rust-lang/rfcs#3555]
i propose introducing a new keyword `letm` as a syntactic sugar for `let mut`. this saves 4 characters.

**Comment by petar-dambovaliev** [comment]
I don't think this is a good idea. There are many other places where you could save characters in the language. Rust already keeps a good balance of not writing too many characters but also not too few, so it's not a burden but also readable.

**Comment by SOF3** [comment]
If typing it is an issue for you, you could propose autocompleting `letm` to `let mut` in code editors instead.

Also, there are many occurrences of `mut` for bindings (e.g. parameters, `match`, `let Foo(mut field)`) that you cannot save the character for, and possibly (citation needed) `&mut` is way more prevalent than `let mut` if you want to save characters somewhere.
