### ISSUE TITLE
why was my rfc closed?

### ISSUE THREAD

**Issue by mikozdravkovski** [rust-lang/rfcs#3744]
Do not make PRs like this.

_Originally posted by @Noratrieb in https://github.com/rust-lang/rfcs/issues/3743#issuecomment-2546886446_
            
Sorry, I am new to this RFC thing. I just got on GitHub and I saw rust was cool, so I wanted to make good first impressions by submitting what I think is a nice idea for Rust. I had chatGPT help me with the formalizing, I admit. What should I correct in the RFC, and may I resend a fixed version?

**Comment by Noratrieb** [comment]
if you want to genuinely help improve the language, go to https://internals.rust-lang.org and talk about the problems you want to solve
