### ISSUE TITLE
META: clarify when an RFCs issue is appropriate

### ISSUE THREAD

**Issue by nrc** [rust-lang/rfcs#375]
Or rather when to use the following options for ideas:
- a discuss post
- an RFCs issue
- an RFC (i.e., a PR to the RFCs repo)
- an issue on rust-lang/rust
- a blog post

Noting that we have a process for closing RFC PRs but not RFC issues (for now).

**Comment by Centril** [comment]
It seems to me this issue has outlived it's usefulness as nothing has happened here for 4 years.
