### ISSUE TITLE
Rust's system for globals / constants is not ideal

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rfcs#398]
It has pointless restrictions that are forever going to hurt code generation and expressiveness like `const` being an rvalue and `static` having a significant address. There were better ways of accomplishing the goal of allowing internal mutability in `static` and initialization of types with internal mutability with `const` without it being broken. The only restriction really needed for `const` was forbidden the definition of external ones. Whether or not the underlying variable is marked as `constant` in LLVM is an *implementation detail*. Taking an address of a `const` containing `UnsafeCell` could have been forbidden but it is not strictly necessary - `const` could allow internal mutability just like `const` variables in C++.

**Comment by nikomatsakis** [comment]
Closing in favor of #1056, which describes a specific, backwards compatible change that would (I believe) achieve the aims described here.
