### ISSUE TITLE
Add a readv/writev-like functionality to IO libraries

### ISSUE THREAD

**Issue by jorisgio** [rust-lang/rfcs#410]
POSIX has 4 functions named readv/writev/preadv/pwritev to allow reading and writting a vector of memory buffers into a filedescriptor. It looks like Windows provides the same functionality with the ReadFileScatter and WSASend function family.

As far as I can tell, rust doesn't allow such a thing yet. This is although quite useful to write server software. For instance if you want to transfer data from the filesystem into the network and add a header using an udp socket, you can do this w/o copying data with the writev function. Since the Writer trait or the UdpSocket structure only allow to send a byte slice, to avoid a copy, you need to create a  large enough buffer to store the data and the header, reserve enough space for the header at the beginning, read the data in a subslice, and then write the header.

It's obviously doable, but can become quite hard to deal with when your protocol has arbitrary sized header.

I think such a method in the Reader and Writer traits could be an useful addition. But it probably has to be done early since it's probably not backward compatible.

**Comment by crlf0710** [comment]
`Read::read_vectored` and `Write::write_vectored` are added in 1.36. Maybe this can be closed now? @Centril
