### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by glaebhoerl** [rust-lang/rfcs#415]
We want to add support for garbage collection at some point.

We had a really long discussion about this back on the `rust` repository [here](https://github.com/rust-lang/rust/pull/11399). It also implicates the [design for allocators](https://github.com/rust-lang/rfcs/pull/244).

My own belief is that the best plan would be precise tracing piggybacked off the existing trait and trait object system, i.e. compiler-derived trace routines (`Trace` `impl`s) for each type, as outlined in my comment [here](https://github.com/rust-lang/rust/pull/11399#issuecomment-33124755). This would likely be very performant and avoid the need for any kind of headers on allocations, except for existentials (trait objects), which could/would have a `Trace` vtable pointer similarly to how `Drop` is currently done, i.e. this would also "just fall out" of the trait-based mechanism. By avoiding headers, we could also avoid imposing any costs on code which doesn't use GC.

(I am also not sure that we need to involve LLVM in any way, at least in the first round. My suspicion is that via the borrow checker and the type system (at least once we have static drops), we already have _more_ information than would LLVM. Instead of stack maps, at least in the first iteration, in GC-using code we could have the compiler insert calls to register/unregister stack variables which may potentially contain managed data with the GC, based on borrow checker information.)

**Comment by magicgoose** [comment]
re. opt-in vs opt-out:
selection of opt-out GC was one of the bigger things that "killed" the D language. because it became pretty much impractical to use without GC, because most code depended on it, and then it's not a C++ alternative anymore.

IMO, having GC is fine but then it should be opt-in…
