### ISSUE TITLE
Rename `unimplemented!` to `undefined!`

### ISSUE THREAD

**Issue by bjz** [rust-lang/rfcs#436]
I propose that we rename the `unimplemented!` macro to `undefined!`. This is much easier to type, and follows the the [similar function in Haskell](http://hackage.haskell.org/package/base-4.7.0.1/docs/Prelude.html#v:undefined).

**Comment by alexcrichton** [comment]
Due to this macro now being stabilized and lack of a method to deprecate macros, I'm going to close this.
