### ISSUE TITLE
Allow `type` in `impl`s

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/rfcs#444]
Right now if one adds an extra `<>` arg to the type being impl'd, every single reference to that type within the impl has to be updated. This becomes especially painful while making changes to structs implementing Decoder and Encoder traits due to the large number of functions being passed functions which take Self as a parameter.

Associated types does not help us here because these types are not members of the trait being impl'd, they are simply helpers for the writer of the impl (and their names probably shouldn't escape the impl).

**Comment by Stebalien** [comment]
Triage: Fixed (by https://github.com/rust-lang/rfcs/pull/522) 

/cc @alexcrichton
