### ISSUE TITLE
feature request: delete entries of a map (TreeMap, BTreeMap, etc) while iterating over it

### ISSUE THREAD

**Issue by haberman** [rust-lang/rfcs#460]
I was writing an algorithm the other day where I wanted to be able to delete items from a map as I was iterating over it.

My desired algorithm, in pseudo-code, is basically:

```
iter = map.find(x)
while (true) {
  item = iter.next()
  max = item.foo
  iter.delete();  // Delete current item.
  if (max > y) {  // This could be any application-level predicate.
    break;
  }
}
```

A slight variant that is often important also is: I want to iterate over the whole map, but delete some items and not others based on a user predicate.

After asking on IRC it doesn't appear that there is any way to mutate a map in Rust while iterating over it.
- iterating over the map borrows it, preventing `map.remove()` calls while iterating.
- the iterator itself offers no deleting functionality.
- while the `BTreeMap` `Entry` type allows some amount of mutating directly from `OccupiedEntry` to `VacantEntry`, there is nothing that offers iteration over `Entry` types. The iterators offered only expose (key, value) tuples, not `Entry`s.

The only workaround I can see for this is: while iterating, build a `Vec` of keys I want to delete, and after iteration, delete them. But this turns a constant-space algorithm in to an `O(n)` space algorithm.

C++ offers deleting while iterating via this (admittedly subtle) pattern: http://stackoverflow.com/a/2874533/77070

Possible solutions to the problem in Rust that I can think of:
1. Offer an iterator that can add/delete entries during iteration. There is currently an iterator that exposes mut _entries_, but none AFAICS that is mut with respect to the _container._
2. Offer an iterator over `Entry` types. But this solution is less satisfying because it is very `BTreeMap`-specific.
3. Offer a version of map.remove() that takes an iterator instead of a key... but I guess you'd run into the same problem where you can't call the method because iterating has already borrowed the map.
4. Others? Someone on IRC said something about cursors being a possible solution to this problem?

**Comment by Stebalien** [comment]
An alternative is #1338.

**Comment by Centril** [comment]
Closing in favor of #1338.
