### ISSUE TITLE
Improvements to error trait, Error boxing and Traceback Support

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rfcs#477]
I would like to write an RFC for the general ideas implemented in [rust-incidents](https://github.com/mitsuhiko/rust-incidents) which improves error handling in Rust in a few ways.  Most of it is backwards compatible but a few things are not.

The overview of the changes I have in mind:
# Improved Error Trait

The first change is to the error trait:

``` rust
pub trait Error: 'static + Send {
    fn name(&self) -> &str;
    fn description(&self) -> Option<&str> { None }
    fn detail(&self) -> Option<String> { None }
    fn cause(&self) -> Option<&Error> {  None }
}
```

The big changes are the introduction of `'static` and `name()` as well as the change to `description()` to be an option.  The motivation is the following:
- the `'static` trait bound will allow us to use `TypeId` on errors which is a very useful concept to have for debugging.  `rust-incidents` depends on this.
- mandatory `name()` to give good error formatting errors need names. Description is actually a lot less interesting than name from how I have error formatting in mind. The error formatting is based on the general behavior of Python tracebacks.
- making description optional makes it consistent with `detail()` and has the added benefit that it avoids adding generic and useless descriptions of no descriptions are available.  If the error is already called "File Not Found" the description is often not very important any more.

_This is largely backwards compatible; low impact_
# Introduction of Failure<T>

One problem with errors in rust currently is that they are generally unboxed.  This makes results in the success case way too big. An example is `IoError` which is quite a few words too long.  While `Box<T>`  does not sound too bad, rust-incidents introduces a different box which has the added benefit that it's specific to errors and can support tracebacks in debug builds.

In debug builds it carries a traceback internally, in release builds it just carries a box.

_This is backwards compatible; low impact_
# fail! and try!

The last part is the most controversial.  Currently `try!` can be used with any value.  This would be nice to have as a feature in the future but currently `rust-incidents` does not support it.  The reason for this is the absence of negative trait bounds.  It needs specific implementations for errors and failures to generate tracebacks.

`fail!(a[, b])` expands to a call to `ConstructFailure::construct_failure((a[, b]), DebugInfo)` which can either box things up in a failure, leave it unchanged or augment the traceback stored in a failure box.  Instead of using `FromError` directly, `FromError` calls are placed in `ConstructFailure` methods.

`try!` works similar to it does currently but it uses `fail!` for the `Err()` clause.

Because of the absence negative trait bounds `try!` is currently not backwards compatible.  You can only used it for errors and failures, not for arbitrary values.

_This is not backwards compatible; high impact_

---

Error handling I believe is one of the most important topics to get right before 1.0, at least to the point where we have a way forward.  I understand that 1.0 is coming up and that we need to be careful what to get in, but given that there are plans to stabilize APIs that can produce results we need to be considerate of error handling as a topic.

**Comment by Stebalien** [comment]
@mitsuhiko 
Triage: This RFC issue appears to be academic at this point. Mind closing?
