### ISSUE TITLE
Allow overwriting the panic_fmt language item

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rfcs#513]
If an executable uses a library that is not unwind-safe, the user has to guarantee that the executable does not unwind into the library. The only way to do this reliably is to turn unwinding into aborting. This can be done by overwriting the panic_fmt language item like this:
```rust
#[lang = "panic_fmt"]
pub extern fn rust_begin_unwind(_: &fmt::Arguments, _: &'static str, _: uint) -> ! {
    unsafe { intrinsics::abort() }
}
```
cc #512

**Comment by steveklabnik** [comment]
We now have the ability to compile panics into aborts https://github.com/rust-lang/rfcs/pull/1513
