### ISSUE TITLE
Abstract Return types

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#518]
https://github.com/rust-lang/rfcs/pull/105 was closed, but this is a feature we do want someday.

**Comment by mitchmindtree** [comment]
[New(ish) related proposal](https://github.com/rust-lang/rfcs/pull/1305).

**Comment by glaebhoerl** [comment]
also https://github.com/rust-lang/rfcs/issues/1522

**Comment by mbrubeck** [comment]
Marking this as closed by #1522.
