### ISSUE TITLE
Make an Iterable trait to make it quicker for a programmer to iterate over something

### ISSUE THREAD

**Issue by Kilobyte22** [rust-lang/rfcs#524]
Currently when we want to iterate over an Array we always have to call .iter() on that array. I suggest that there should be a trait to standardize this:  
```rust
pub trait Iterable<T> {
  fn iter(&self) -> Iterator<T>;
}
```
Now, rustc would check in for loops for instances of Iterable<T> and automatically adding a .iter(). This would allow for code like this:  
```rust
let a = ["a", "b", "c"];
for element in a {
  println!("Element: {}", element);
}
```
The old way would obviously still work, this would only be syntactic sugar

**Comment by alexcrichton** [comment]
I believe this was done via `IntoIterator`, so closing.
