### ISSUE TITLE
Start date, PR and issue missing from merged RFC

### ISSUE THREAD

**Issue by ciphergoth** [rust-lang/rfcs#559]
https://github.com/rust-lang/rfcs/blob/master/text/0255-object-safety.md is merged into master but still starts with:

    - Start Date: (fill me in with today's date, YYYY-MM-DD)
    - RFC PR: (leave this empty)
    - Rust Issue: (leave this empty)

AIUI now that this is merged, these should be filled in.

**Comment by huonw** [comment]
Fixed in 02b8290 and baf0ab3 (forgot to do the date the first time), thanks.
