### ISSUE TITLE
Switch rustdoc to Common Markdown

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#620]
<a href="https://github.com/brson"><img src="https://avatars.githubusercontent.com/u/147214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brson](https://github.com/brson)**
_Wednesday Sep 03, 2014 at 22:27 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/16978_

_This issue was labelled with: A-rustdoc, E-easy, I-wishlist in the Rust repository_

---

Assuming this takes off it's probably best to be on the right side of history: http://standardmarkdown.com/. Probably easiest to just make hoedown conformant.

**Comment by mbrubeck** [comment]
This has been implemented behind a flag, and rust-lang/rust#44229 is tracking the plan to enable it by default.
