### ISSUE TITLE
rustdoc: add the ability to copy a skeleton trait impl from a trait doc entry

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#621]
<a href="https://github.com/bjz"><img src="https://avatars.githubusercontent.com/u/695077?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bjz](https://github.com/bjz)**
_Monday Oct 27, 2014 at 23:49 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/18379_

_This issue was labelled with: A-an-interesting-project, A-rustdoc, I-enhancement, I-wishlist in the Rust repository_

---

@wycats mentioned this idea to me a while back when I was fishing for ideas about how to improve rustdoc.

The impl should have the right formatting, and have dummy method impls using the `unimplemented!` macro. Perhaps default methods could come with a comment above them saying that they do not need to be implemented.

**Comment by Centril** [comment]
Refiled to https://github.com/rust-lang-nursery/rls/issues/1081; closing this.
