### ISSUE TITLE
Occurrences of a libstd or libextra item in the tutorial and manual should link to the docs for it

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#623]
<a href="https://github.com/lkuper"><img src="https://avatars.githubusercontent.com/u/535218?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lkuper](https://github.com/lkuper)**
_Monday May 27, 2013 at 04:42 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/6758_

_This issue was labelled with: A-rustdoc, E-hard, I-wishlist in the Rust repository_

---

Masklinn recently [suggested on rust-dev](https://mail.mozilla.org/pipermail/rust-dev/2013-May/004139.html) that it would be nice to have cross-linking within the generated HTML docs.  E.g., an occurrence of "`println`" in the tutorial would be a link to [here](http://static.rust-lang.org/doc/core/io.html#function-println) (if I understand the suggestion correctly).  We could do this cross-linking for all top-level items: types, traits, functions, impls, etc.

I wouldn't expect this to happen for code blocks, just for inline code.  Ideally, there would also be a way to turn it off -- both in the sense that we might want to be able to tell rustdoc not to do cross-linking on a particular run (to make the docs build faster), and in the sense that we might want to be able to specify that particular occurrences should never be cross-linked (because after a point it might hinder readability). 

Presumably we'd also eventually want this cross-linking within the documentation itself, too, as well as in the tutorial and manual.

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/43466.
