### ISSUE TITLE
Figure out a way to keep track of attributes

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#626]
<a href="https://github.com/brson"><img src="https://avatars.githubusercontent.com/u/147214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brson](https://github.com/brson)**
_Sunday Jun 23, 2013 at 05:25 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/7318_

_This issue was labelled with: I-wishlist in the Rust repository_

---

There are a lot of attributes in use. They are nearly undocumentedand impossible to catalog automatically.

The wiki is out of date: https://github.com/mozilla/rust/wiki/Doc-attributes

**Comment by Centril** [comment]
Defined in https://github.com/rust-lang-nursery/reference/blob/master/src/attributes.md.
Closing as done.
