### ISSUE TITLE
More and better benchmarks are needed

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#627]
<a href="https://github.com/cmr"><img src="https://avatars.githubusercontent.com/u/704250?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cmr](https://github.com/cmr)**
_Monday Jul 01, 2013 at 18:50 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/7532_

_This issue was labelled with: A-an-interesting-project, A-benchmarks, A-testsuite, E-easy, I-wishlist in the Rust repository_

---

We have few good, solid benchmarks that stress a single part of the codegen or libraries. These are necessary to be able to be able to easily spot perfomance regressions, as well as have a good quantitative data about Rust's performance.

Benchmarks should cover both space and time characteristics, and should use the built-in bench runner where possible. Some ideas:
- Allocating an object with a destructor
- Allocating a @-ptr
- Destructuring an enum/struct/tuple/tuple struct/vector
- Pattern matching
- Numeric manipulation (should be covered fairly well by the current shootout stuff, but should be extracted)
- Data structure manipulation (vec benchmarks etc, similar to what `core-map` and friends do)
- String manipulation
- Method call
- Trait object method call
- Task communication (like `pingpong` does) with the various primitives (one-shots, streams, protocols)
- Logging

An important note: these benchmarks aren't intended for comparison to other languages (although they could be useful for that in the future), but for _tracking the performance of Rust_.

**Comment by Centril** [comment]
Today we have criterion.rs and other libs.
So I'm closing this.
