### ISSUE TITLE
Make unwinding task-independent

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#632]
<a href="https://github.com/brson"><img src="https://avatars.githubusercontent.com/u/147214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brson](https://github.com/brson)**
_Friday Feb 07, 2014 at 01:44 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/12080_

_This issue was labelled with: A-runtime, I-wishlist in the Rust repository_

----

For the sake of embedding applications it would be nice if Rust's unwinding implementation was not directly coupled to the task abstraction.

Right now unwinding is mostly just try/catch, but it also sets a flag on the task to indicate that the task is failing. It would be better if std could fulfill its unwinding obligations without involving the task.

**Comment by alexcrichton** [comment]
This has been done!
