### ISSUE TITLE
Error message reporting should show overall progress to be less demoralizing

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#633]
<a href="https://github.com/larsbergstrom"><img src="https://avatars.githubusercontent.com/u/475847?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [larsbergstrom](https://github.com/larsbergstrom)**
_Monday Feb 10, 2014 at 22:06 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/12166_

_This issue was labelled with: I-wishlist in the Rust repository_

---

Right now, rustc will report error messages only up through the highest phase it could complete. That leads developers to think they nearly have worked through all of the compilation errors only to be hit by another huge lump of them after they get to the next phase. One of our external Servo contributors described this as, "demoralizing because it looks like the number of errors is decreasing, but in reality the parser just hasn't gotten past the second line."

Ideal would obviously be to report an overall number that was more representative of the total number of errors, but even showing a measure of the overall progress (cmr suggested a counter like "125 errors (stage 3/N)") would be a huge improvement.

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/12166.
