### ISSUE TITLE
Develop a semantic search/patch tool

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#666]
<a href="https://github.com/kmcallister"><img src="https://avatars.githubusercontent.com/u/444997?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kmcallister](https://github.com/kmcallister)**
_Thursday Oct 16, 2014 at 16:51 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/18094_

_This issue was labelled with: A-an-interesting-project, A-tools, E-hard in the Rust repository_

---

Something like [Coccinelle](http://coccinelle.lip6.fr/).

**Comment by Centril** [comment]
I believe `rust fix` fits this description to a degree so I'm closing this for now.
