### ISSUE TITLE
`size_hint` should be able to return a lower bound that is infinite

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#677]
<a href="https://github.com/vks"><img src="https://avatars.githubusercontent.com/u/33460?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vks](https://github.com/vks)**
_Friday Nov 07, 2014 at 22:01 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/18751_

_This issue was labelled with: A-iterators, A-libs, B-RFC in the Rust repository_

----

Taken from the standard library:

```rust
impl<A: Add<A, A> + Clone> Iterator<A> for Counter<A> {
    [...]
    #[inline]
    fn size_hint(&self) -> (uint, Option<uint>) {
        (uint::MAX, None) // Too bad we can't specify an infinite lower bound
    }
}
```

Some iterators are infinite, `size_hint` should be able to return `(None, None)` for that. This warrants changing the type signature to `(Option<uint>, Option<uint>)`.

**Comment by Stebalien** [comment]
@steveklabnik 

Triage: This issue is largely academic at this point (breaking change). Mind closing?
