### ISSUE TITLE
Improving an error message: "cannot bind by-move into a pattern guard"

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#684]
<a href="https://github.com/catamorphism"><img src="https://avatars.githubusercontent.com/u/427212?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [catamorphism](https://github.com/catamorphism)**
_Saturday Jan 26, 2013 at 20:41 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/4649_

_This issue was labelled with: A-diagnostics, A-windows, B-RFC, I-papercut in the Rust repository_

---

Based on an IRC conversation just now, I can think of two ways to improve this error message:
1. Because pattern guards use the "if" keyword, someone may have written one by accident. Then, if they see this error message, they're going to ask "what's a pattern guard"? The error could explain this (it's a little hard to figure out right now since the entire pattern gets underlined, not the guard).
2. Probably more importantly, the error should suggest what to do to fix it.

The error in question is in `rustc::middle::check_match`.

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/45600.
