### ISSUE TITLE
Decide on (and implement) which parts of the AST can get stability attributes

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#687]
<a href="https://github.com/huonw"><img src="https://avatars.githubusercontent.com/u/1203825?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [huonw](https://github.com/huonw)**
_Tuesday Sep 03, 2013 at 23:56 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/8967_

_This issue was labelled with: A-attributes, A-lint, B-RFC in the Rust repository_

---

As of #8921, the compiler checks the attributes on structs, enum variants (not enums themselves) and functions. Definitely required: methods (#8961) and mods (#8962).

Up for discussion:
- traits
- enums
- impls (both `impl Type` and `impl Trait for Type`)
- struct fields
- `type` aliases.
- foreign fns
- anything else that can take attributes in the ast

(Part of #6875.)

**Comment by petrochenkov** [comment]
This is implemented long ago.
Everything that can be named is checked for stability, except for reexports (tracked by https://github.com/rust-lang/rust/issues/23937).
