### ISSUE TITLE
AdditiveIterator and MultiplicativeIterator should be implemented on all iterators with Add/Mul items

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#696]
<a href="https://github.com/Tobba"><img src="https://avatars.githubusercontent.com/u/1667853?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tobba](https://github.com/Tobba)**
_Tuesday Jan 13, 2015 at 15:17 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/21094_

_This issue was labelled with: A-iterators, A-libs, P-low in the Rust repository_

----

Currently both AdditiveIterator and MultiplicativeIterator are implemented on specifically all iterators over the base integer types. This is strange as they could be generically implemented over all iterators with items implementing Add/Mul. Moreover, the concepts of summation and products aren't exactly limited to iterators (although these traits actually have no requirement of being implemented on iterators).

**Comment by alexcrichton** [comment]
This has been done!
