### ISSUE TITLE
Write a TRPL chapter on inline assembly

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#701]
<a href="https://github.com/kmcallister"><img src="https://avatars.githubusercontent.com/u/444997?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kmcallister](https://github.com/kmcallister)**
_Monday Jan 12, 2015 at 20:28 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/21039_

_This issue was labelled with: A-docs, A-inline-assembly in the Rust repository_

---

Take what little we have on `asm!()` from "Unsafe Code", and greatly expand it.

**Comment by mbrubeck** [comment]
Now part of the unstable book: https://doc.rust-lang.org/nightly/unstable-book/language-features/asm.html
