### ISSUE TITLE
Add an option to rustdoc to deny warnings and use it in std

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#703]
<a href="https://github.com/brson"><img src="https://avatars.githubusercontent.com/u/147214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brson](https://github.com/brson)**
_Friday Jan 09, 2015 at 02:16 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/20787_

_This issue was labelled with: A-rustdoc, E-easy in the Rust repository_

----

In https://github.com/rust-lang/rust/pull/20786 I'm recommending removing this feature of rustdoc as a blanket policy. It should be optional. Perhaps something even more generic like the `-D`, `-F`, of rustc, but applicable to doc tests.

**Comment by alexcrichton** [comment]
This was done!
