### ISSUE TITLE
Add grapheme_at{,_reverse} functions to UnicodeStr

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#704]
<a href="https://github.com/mahkoh"><img src="https://avatars.githubusercontent.com/u/1882250?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahkoh](https://github.com/mahkoh)**
_Friday Jan 09, 2015 at 16:40 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/20810_

_This issue was labelled with: A-collections, A-libs in the Rust repository_

----

**Comment by alexcrichton** [comment]
These functions were moved to an external crate, so I'm going to close this.
