### ISSUE TITLE
No unsafe slicing

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#708]
<a href="https://github.com/cgaebel"><img src="https://avatars.githubusercontent.com/u/128969?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cgaebel](https://github.com/cgaebel)**
_Tuesday Dec 16, 2014 at 02:16 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/19901_

_This issue was labelled with: A-collections, A-libs, I-wishlist, P-low in the Rust repository_

----

There's currently no version of `slice`, `slice_from`, `slice_to`, `slice_mut`, `slice_from_mut`, `slice_to_mut`, `split_at` that doesn't bounds check.

**Comment by Stebalien** [comment]
Triage: Fixed by #1679
