### ISSUE TITLE
String/str should not support sliced indexing

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rfcs#725]
A common question from Rust newbies is why `String`/`str`  don't allow simple indexing, like this:

```rust
let foo = "foobar";
let x = foo[0];
```

The answer has always been that `foo[0]` is both ambiguous and dangerous given that `str` is a UTF-8 string: it could be a byte offset returning a char, a byte offset returning a u8, a codepoint index returning a char, etc., each having its own potential pitfalls of panicking or slowness.

If `foo[0]` is not allowed on `str`, `foo[m..n]` and `foo[..n]` and similar such "sliced" indexing operations using `Index<RangeTo>` and `Index<RangeFrom>` and `Index<Range>` shouldn't be allowed either.

(It's also a bit strange that both `String` and `str` impl these traits; since `String` is `Deref<str>`, shouldn't it only be needed on `str`?)

**Comment by bluss** [comment]
I think this can be closed, since rust is now stable with string slicing.

> (It's also a bit strange that both String and str impl these traits; since String is Deref<str>, shouldn't it only be needed on str?)

This is true in nongeneric code, but in generic code, String would not fit the requirement `S: Index<Range<usize>>` without an explicit impl (that said, it's probably not the trait bound you'd want to use).
