### ISSUE TITLE
Deriving may want to ignore marker fields

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#726]
<a href="https://github.com/kballard"><img src="https://avatars.githubusercontent.com/u/714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kballard](https://github.com/kballard)**
_Sunday May 18, 2014 at 00:05 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/14268_

_This issue was labelled with:  in the Rust repository_

---

Marker fields are used to provide extra information about types, including opting out of `Copy`, `Send`, and `Share` bounds. However, the presence of a marker field can prevent the ability to `#[derive]` traits for that type. For example, `core::kinds::marker::NoCopy` only implements `Clone` and `Eq` (according to rustdoc; I am unsure if there are any libstd traits it implements because rustdoc doesn't show cross-crate traits). This means that any struct with a `NoCopy` field cannot e.g. derive `Show`, or `Ord`, or other useful traits.

I think the right solution here is to simply not consider the marker fields when deriving traits, with the only exception being `Clone`. Every other trait should just pretend that field doesn't exist.

**Comment by Centril** [comment]
I don't think this applies anymore / is not actionable so I am closing this.
