### ISSUE TITLE
Support more hashsum algorithm

### ISSUE THREAD

**Issue by caizixian** [rust-lang/rfcs#729]
Currently, there is only sha256. Could you please consider supporting md5,sha1,etc.
rust-lang/rust#21572

**Comment by gsingh93** [comment]
I think the reason Rust has SHA256 is because it actually needs it in the compiler itself. Providing various hashing algorithms seems like a job for an external library, not a standard library. In fact, I think [rust-crypto](https://github.com/DaGenix/rust-crypto/) supports these functions.

**Comment by caizixian** [comment]
Having these in std lib does make sense because it would be handy.

**Comment by gsingh93** [comment]
Having every external library on crates.io in the standard library would be
convenient as well, but that's not practical. "Handy" isn't really a reason
to include something in the standard library. It should be something that
people use often and is common. SHA1 and MD5 don't really qualify here.

**Comment by raincious** [comment]
@gsingh93 Well, I do not agree with that :smile: 

You see, encryption as well hash is important and critical, so it's not just for convenient, but also for  security as everyone can make their own encryption crates and create bugs during that progress. 

Discover and fix every each buggy crate takes time and efforts, some people may even needs to move to another crate to get safety.

A standard lib is needed as it will concentrate the problem in one single place, so if is there is a bug, it will have greater chance to be discovered and fixed right soon after that.

**Comment by Centril** [comment]
I don't think we support sha256 anymore in libstd and there are crypto libs on crates.io so I am closing this.
