### ISSUE TITLE
Compile Time Execution

### ISSUE THREAD

**Issue by Vikaton** [rust-lang/rfcs#732]
Any plans on implementing this in Rust? nimlang has this cool feature and Im wondering if Rust will have it soon.

**Comment by DiamondLovesYou** [comment]
You can already do it with a macro implemented in a compiler plugin.

**Comment by Ap0ph1s** [comment]
Thats not as General as a full CTFE though.

**Comment by jmesmon** [comment]
And using compiler plugins means we need to split our code that runs at different times into different files, which doesn't help much when we just want to initialize some datastructures that the code is making use of.

(Not to mention that we don't actualy have a documented/stable plugin interface)

**Comment by Ap0ph1s** [comment]
Isnt it possible to do it the way Nim does it? http://hookrace.net/blog/what-is-special-about-nim/#run-regular-code-at-compile-time

**Comment by reem** [comment]
This has been noted by the community many times as a desired post-1.0 feature.

**Comment by SimonSapin** [comment]
I think this can be closed in favor of https://github.com/rust-lang/rfcs/pull/911

**Comment by petrochenkov** [comment]
MIRI is merged into rustc and is will be used for all const evaluation soon (https://github.com/rust-lang/rust/pull/46882), I don't think there's value in keeping this issue open.
