### ISSUE TITLE
Support MSP430 architecture and target

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#758]
<a href="https://github.com/alexchandel"><img src="https://avatars.githubusercontent.com/u/637714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexchandel](https://github.com/alexchandel)**
_Thursday Aug 28, 2014 at 22:20 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/16831_

_This issue was labelled with:  in the Rust repository_

----

The MSP430 architecture is a common target in embedded programming, namely TI's MSP430 microcontroller family, and should be targetable by Rust. Support for MSP430 was recently [added to LLVM](http://llvm.org/docs/doxygen/html/dir_08aa625df1bb9fc877a11230539de4c0.html), although absent LLD support the MSP430 binutils is still necessary (as for all platforms). Previously, the only way to target MSP430 was using the custom GCC toolchain.

**Comment by alexcrichton** [comment]
I think we probably don't want a tracking issue per-platform that would be nice to support one day, and our policy right now is that we're more than willing to accept patches to port to new OSes but we will likely not actively pursue it ourselves. As a result I'm going to close this.
