### ISSUE TITLE
Marker types should be FFI-safe

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#760]
<a href="https://github.com/mzabaluev"><img src="https://avatars.githubusercontent.com/u/1198919?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mzabaluev](https://github.com/mzabaluev)**
_Wednesday Oct 01, 2014 at 09:56 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/17679_

_This issue was labelled with:  in the Rust repository_

---

If I get a struct by pointer from a foreign library, and I know the structure cannot safely be copied because the actual object is larger than the struct, I want to declare it as something like this:

``` rust
#[repr(C)]
struct A {
    // ...
    no_copy: std::kinds::marker::NoCopy;
}
```

Now the compiler complains at use site that the struct is not foreign-function-safe.
As the markers are zero-sized, they have no bearing on the layout and no consequences for the structure data, so they, as long as any other zero-sized structures, should not waive FFS.

@thestinger suggests the same should apply to structures with one field as well, but I'm not so certain about that: there could be optimizations regarding alignment which would not be compatible with the (default) C ABI.

**Comment by mbrubeck** [comment]
See also #750.

**Comment by Centril** [comment]
`std::kinds::marker::NoCopy` does not exist so I am closing this.
