### ISSUE TITLE
Request: add prefix_sum and prefix_product to AdditiveIterator and MultipilicativeIterator

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#763]
<a href="https://github.com/Undeterminant"><img src="https://avatars.githubusercontent.com/u/1756968?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Undeterminant](https://github.com/Undeterminant)**
_Tuesday Nov 04, 2014 at 21:38 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/18631_

_This issue was labelled with:  in the Rust repository_

---

I found myself coding these up and figured that it would make sense to have them by default.

**Comment by Centril** [comment]
We don't have `AdditiveIterator` so this is not actionable.
