### ISSUE TITLE
Non-terminal `ident` should not match keywords

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rfcs#772]
This example macro is currently not usable:

``` rust
macro_rules! idents_followed_by_keyword {
    ($($slot:ident,)+ else) => ($(let $slot = 0;)+);
}

fn main() {
    idents_followed_by_keyword!(_a, else);
}
```

The reason is that the `ident` format specifier makes no distinction between keywords and bona fide identifiers, resulting in ambiguity when the matcher meets `else`. As keywords cannot be used in place of identifiers in transcription, it should break no existing macro if `ident` is changed to exclude keywords.

This will permit more useful, cleaner macro syntaxes.

**Comment by petrochenkov** [comment]
This works as expected and can't be changed now.
See https://github.com/rust-lang/rust/issues/27899
