### ISSUE TITLE
sleep(abstime) is missing

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#783]
<a href="https://github.com/thestinger"><img src="https://avatars.githubusercontent.com/u/1505226?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thestinger](https://github.com/thestinger)**
_Tuesday Mar 04, 2014 at 22:28 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/12691_

_This issue was labelled with: A-libs, I-wishlist in the Rust repository_

---

This is required for accurate loops without jitter. It must also provide the option of using a monotonic clock.

**Comment by Centril** [comment]
Should be possible with https://doc.rust-lang.org/nightly/std/time/struct.Instant.html and https://doc.rust-lang.org/nightly/std/thread/fn.sleep.html today I think so I'm closing this as completed.
