### ISSUE TITLE
ProcessExit should have method `.code() -> int`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#787]
<a href="https://github.com/kballard"><img src="https://avatars.githubusercontent.com/u/714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kballard](https://github.com/kballard)**
_Monday Sep 29, 2014 at 00:54 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/17618_

_This issue was labelled with: A-libs, I-enhancement in the Rust repository_

----

When a process exits due to a signal, and that process was launched by a shell, the shell typically treats the exit status of the process to be 128 + the signal number. This is true for bash, fish, and zsh (I haven't tested other shells). Based on this, it would be convenient for `ProcessExit` to have a method

```rust
fn code(&self) -> int;
```

that replicates this behavior, in order to make it easier for programs that don't want to have to care about the distinction between a signal and a normal exit.

**Comment by alexcrichton** [comment]
I believe this has long since been addressed, so closing
