### ISSUE TITLE
Expose an UTF-8 checking function that returns the index of the error

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#860]
<a href="https://github.com/Jurily"><img src="https://avatars.githubusercontent.com/u/1728602?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jurily](https://github.com/Jurily)**
_Monday Feb 10, 2014 at 22:43 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/12168_

_This issue was labelled with: A-libs in the Rust repository_

----

Use case:

- reporting the position of the error to the user

Possible candidates: 

- mark `first_non_utf8_index()` as public
- change `from_utf8{_owned}`'s return type from  `Option` to `Result<_, uint>`

Since it's possible to recover from such an error, it would also be nice if these returned all encoding errors.

**Comment by aturon** [comment]
This has actually been resolved: http://static.rust-lang.org/doc/master/std/str/fn.from_utf8.html
