### ISSUE TITLE
Add a way to reset MemWriter

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#872]
<a href="https://github.com/SiegeLord"><img src="https://avatars.githubusercontent.com/u/480550?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SiegeLord](https://github.com/SiegeLord)**
_Friday Aug 01, 2014 at 11:54 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/16167_

_This issue was labelled with: A-io, A-libs in the Rust repository_

---

MemWriter recently lost its ability to seek due to speed concerns, which removed any way of resetting/truncating it (i.e. seeking backwards). Could this be added? A possible API/implementation would be:

``` rust
// Does nothing if new_len is greater than current length
pub fn truncate(&mut self, new_len: uint) { self.buf.truncate(new_len); }
```

Alternatively, perhaps a new constructor could be added which would wrap an existing `Vec` which would allow me to do this:

``` rust
let writer = MemWriter::new();
let mut vec = writer.unwrap();
vec.truncate(new_len);
let writer = MemWriter::wrap(vec);
```

@erickt, I recall talking to you about this on IRC, so you may have some thoughts.

**Comment by Stebalien** [comment]
Triage: There is no `MemWriter`. As far as I can tell, this is now `Cursor<Vec<u8>>` (which supports `Seek`) so this issue should be moot.
