### ISSUE TITLE
[bikeshed] calling convention names

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rfcs#887]
Currently we have following calling conventions: cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call. Two of them are upper case, namely “Rust” and “C”. 

I doubt there’s many users who would specify `Rust` CC explicitly and `C` CC should not be specified at all either because it is default for `extern` functions.

Is renaming them to lower case variants (possibly after deprecation period until 1.0) an acceptable breaking change?

**Comment by Centril** [comment]
This doesn't seem actionable and there has been no movement since 2015 so I'm closing this.
