### ISSUE TITLE
fs::DirEntry does not provide a relative path

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rfcs#934]
<a href="https://github.com/hugoduncan"><img src="https://avatars.githubusercontent.com/u/54043?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hugoduncan](https://github.com/hugoduncan)**
_Sunday Mar 01, 2015 at 12:29 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/22926_

_This issue was labelled with: A-io, A-libs in the Rust repository_

----

In some situations, e.g. copying a sub-tree, a relative path is required for an entry returned by `read_dir` or `walk_dir`.  Consider changing `path` to return a relative path, or adding a `rel_path` function to provide it if the current `path` semantics should be preserved.

The [`fs::DirEntry::path` function](http://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.path) returns a full path, with the root of the `read_dir` or `walk_dir` call prepended.  Recovering a relative path form the full path seems relatively expensive (`entry.path().relative_from(root).unwrap()`), espescially since `DirEntry::path` has to explicitly join the root in the first place.

**Comment by GuillaumeGomez** [comment]
I actualoly opened a RFC for this issue (the #927).
