### ISSUE TITLE
Stabilize raw::Slice

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rfcs#945]
Stabilize raw::Slice and the layout of slices.

Knowing the layout of slices is necessary for efficient ffi code.

**Comment by Stebalien** [comment]
Triage: raw::Slice has been deprecated in favor of `slice::from_raw_parts`, `[T]::len`, and `[T]::as_ptr`. See discussion on https://github.com/rust-lang/rust/issues/27751 and PR https://github.com/rust-lang/rust/pull/32804

**Comment by alexcrichton** [comment]
Indeed!
